import { Injectable } from '@angular/core';
import { Salario } from './salario';


let salarios: Salario[] = [
  {
    id:1,
    nombre:'juan',
    apellido:'gomez',
    email:'ju@j.com',
    telefono:'1000-0000',
    salario:2000,
  },
  {
    id:2,
    nombre:'jose',
    apellido:'servantes',
    email:'jo@j.com',
    telefono:'2000-0000',
    salario:2000,
  },
  {
    id:3,
    nombre:'joel',
    apellido:'colochio',
    email:'joe@j.com',
    telefono:'3000-0000',
    salario:2000,
  },
  {
    id:4,
    nombre:'julian',
    apellido:'perez',
    email:'jul@j.com',
    telefono:'4000-0000',
    salario:2000,
  },
  {
    id:5,
    nombre:'alberto',
    apellido:'vasquez',
    email:'alb@j.com',
    telefono:'5000-0000',
    salario:2000,
  },
  {
    id:6,
    nombre:'gamel',
    apellido:'santino',
    email:'joe@j.com',
    telefono:'6000-0000',
    salario:2000,
  },
  {
    id:7,
    nombre:'yancy',
    apellido:'alvarado',
    email:'yan@j.com',
    telefono:'7000-0000',
    salario:2000,
  },
  {
    id:8,
    nombre:'mile',
    apellido:'interiano',
    email:'mil@j.com',
    telefono:'8000-0000',
    salario:2000,
  },
  {
    id:9,
    nombre:'nohe',
    apellido:'interiano',
    email:'noh@j.com',
    telefono:'9000-0000',
    salario:2000,
  },
  {
    id:10,
    nombre:'xeres',
    apellido:'hernandez',
    email:'xer@j.com',
    telefono:'1000-0000',
    salario:2000,
  },
  {
    id:11,
    nombre:'santiago',
    apellido:'peruano',
    email:'san@j.com',
    telefono:'1100-0000',
    salario:2000,
  },
  {
    id:12,
    nombre:'arenita',
    apellido:'mejias',
    email:'are@j.com',
    telefono:'1200-0000',
    salario:2000,
  },
  {
    id:13,
    nombre:'tori',
    apellido:'sanders',
    email:'tor@j.com',
    telefono:'1300-0000',
    salario:2000,
  },
  {
    id:14,
    nombre:'sondic',
    apellido:'armadillo',
    email:'son@j.com',
    telefono:'1400-0000',
    salario:2000,
  },
  {
    id:15,
    nombre:'mile',
    apellido:'interiano',
    email:'mil@j.com',
    telefono:'8000-0000',
    salario:2000,
  },
  {
    id:16,
    nombre:'xenia',
    apellido:'salanmanca',
    email:'xe@j.com',
    telefono:'1600-0000',
    salario:2000,
  },
  {
    id:17,
    nombre:'sandra',
    apellido:'posada',
    email:'sa@j.com',
    telefono:'1700-0000',
    salario:2000,
  },
  {
    id:18,
    nombre:'teresino',
    apellido:'tornez',
    email:'ter@j.com',
    telefono:'1800-0000',
    salario:2000,
  },
  {
    id:19,
    nombre:'francisco',
    apellido:'larios',
    email:'fl@j.com',
    telefono:'1900-0000',
    salario:2000,
  },
  {
    id:20,
    nombre:'fred',
    apellido:'fernandez',
    email:'fr@j.com',
    telefono:'2000-0000',
    salario:2000,
  },
  {
    id:21,
    nombre:'carlos',
    apellido:'interiano',
    email:'car@j.com',
    telefono:'2100-0000',
    salario:2000,
  },
  {
    id:22,
    nombre:'trico',
    apellido:'truco',
    email:'tric@j.com',
    telefono:'2200-0000',
    salario:2000,
  },
  {
    id:23,
    nombre:'tristan',
    apellido:'paz',
    email:'paz@j.com',
    telefono:'2300-0000',
    salario:2000,
  },
  {
    id:24,
    nombre:'trabinio',
    apellido:'trapo',
    email:'trab@j.com',
    telefono:'2400-0000',
    salario:2000,
  },
  {
    id:25,
    nombre:'troni',
    apellido:'velasquez',
    email:'tron@j.com',
    telefono:'2500-0000',
    salario:2000,
  },
];

@Injectable({
  providedIn: 'root'
})
export class SalarioService {
  
  constructor() { }
  
  getSalarios(): Salario[] {
    return salarios.slice();
  }
}
